---
version: 2
updates:
  - package-ecosystem: npm
    directories:
      - /
      - /test
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily