---
version: 2
updates:
  - package-ecosystem: docker-compose
    directories:
      - /docker
    schedule:
      interval: daily
  - package-ecosystem: docker
    directories:
      - /docker
    schedule:
      interval: daily
  - package-ecosystem: npm
    directories:
      - /
      - /test
    schedule:
      interval: daily
