env:
  es2022: true,
  node: true

extends:
  - eslint:recommended
  - prettier
  - plugin:@typescript-eslint/recommended

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 13
  sourceType: module

plugins:
  - "@typescript-eslint"
  - prettier

rules:
  indent: 
    - error
    - 4
  linebreak-style: 
    - error
    - unix
  quotes: 
    - error
    - double
  semi: 
    - error
    - always
  prettier/prettier: 1
