---
name: Build, test and lint
on:
  push: 
    tags:
      - '*'
  
jobs:
  lint:
    # Excute eslint & prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
  compile:
    # Compile with TSC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build  
  doc:
    needs: ['compile', 'lint']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run docs
        run: npm run gendocs
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: docs/
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Gen changelog
        run: bash .github/bin/genlog.sh
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ env.GITHUB_WORKSPACE }}/changelog.txt
          token: ${{ secrets.GITHUB_TOKEN }}
  publish_package:
    needs: ["compile", "lint", "doc"]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          scope: '@federation-interservices-d-informatique'
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

